# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='images.Comments'),
        ),
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='images.Profile'),
        ),
    ]
