# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20190517_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pix/'),
            preserve_default=False,
        ),
    ]
