# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20190517_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
